-- MySQL Script generated by MySQL Workbench
-- Sun Dec  8 16:00:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema voting_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voting_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voting_app` DEFAULT CHARACTER SET utf8mb4;
USE `voting_app` ;

-- -----------------------------------------------------
-- Table `voting_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`user` (
  `UserID` CHAR(36) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `CreatedBy` CHAR(36) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ModifiedBy` CHAR(36) NULL DEFAULT NULL,
  `ModifiedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CurrentVersion` VARCHAR(45) NOT NULL DEFAULT 'g1',
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`vote` (
  `VoteID` CHAR(36) NOT NULL,
  `VoteTitle` VARCHAR(255) NOT NULL,
  `IsSendQrEmail` TINYINT(1) NULL DEFAULT '0',
  `IsRequireName` TINYINT(1) NULL DEFAULT '0',
  `TotalJoiner` INT NULL DEFAULT '0',
  `UserID` CHAR(36) NULL DEFAULT NULL,
  `VoteTime` INT NOT NULL,
  `CreatedBy` CHAR(36) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ModifiedBy` CHAR(36) NULL DEFAULT NULL,
  `ModifiedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `VoteStatus` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`VoteID`),
  INDEX `vote_ibfk_1` (`UserID` ASC) VISIBLE,
  CONSTRAINT `vote_ibfk_1`
    FOREIGN KEY (`UserID`)
    REFERENCES `voting_app`.`user` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`question` (
  `QuestionID` CHAR(36) NOT NULL,
  `QuestionTitle` VARCHAR(255) NOT NULL,
  `IsMultiAnswer` TINYINT(1) NULL DEFAULT '0',
  `IsAnswerAddable` TINYINT(1) NULL DEFAULT '0',
  `VoteID` CHAR(36) NULL DEFAULT NULL,
  `UserID` CHAR(36) NULL DEFAULT NULL,
  `CreatedBy` CHAR(36) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ModifiedBy` CHAR(36) NULL DEFAULT NULL,
  `ModifiedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`QuestionID`),
  INDEX `question_ibfk_1` (`VoteID` ASC) VISIBLE,
  INDEX `question_ibfk_2` (`UserID` ASC) VISIBLE,
  CONSTRAINT `question_ibfk_1`
    FOREIGN KEY (`VoteID`)
    REFERENCES `voting_app`.`vote` (`VoteID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `question_ibfk_2`
    FOREIGN KEY (`UserID`)
    REFERENCES `voting_app`.`user` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`answer` (
  `AnswerID` CHAR(36) NOT NULL,
  `QuestionID` CHAR(36) NOT NULL,
  `AnswerContent` TEXT NULL DEFAULT NULL,
  `IsCustom` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`AnswerID`),
  INDEX `answer_ibfk_1` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `answer_ibfk_1`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `voting_app`.`question` (`QuestionID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`email` (
  `EmailID` CHAR(36) NOT NULL,
  `EmailAddress` VARCHAR(255) NOT NULL,
  `VoteID` CHAR(36) NULL DEFAULT NULL,
  `UserID` CHAR(36) NULL DEFAULT NULL,
  `CreatedBy` CHAR(36) NULL DEFAULT NULL,
  `CreatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ModifiedBy` CHAR(36) NULL DEFAULT NULL,
  `ModifiedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`EmailID`),
  INDEX `email_ibfk_1` (`VoteID` ASC) VISIBLE,
  INDEX `email_ibfk_2` (`UserID` ASC) VISIBLE,
  CONSTRAINT `email_ibfk_1`
    FOREIGN KEY (`VoteID`)
    REFERENCES `voting_app`.`vote` (`VoteID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `email_ibfk_2`
    FOREIGN KEY (`UserID`)
    REFERENCES `voting_app`.`user` (`UserID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`result` (
  `ResultID` CHAR(36) NOT NULL,
  `SubmitterName` VARCHAR(255) NULL DEFAULT NULL,
  `VoteID` CHAR(36) NULL DEFAULT NULL,
  `EmailID` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`ResultID`),
  INDEX `vote_VoteID_idx` (`VoteID` ASC) VISIBLE,
  INDEX `email_EmailID_idx` (`EmailID` ASC) VISIBLE,
  CONSTRAINT `email_EmailID`
    FOREIGN KEY (`EmailID`)
    REFERENCES `voting_app`.`email` (`EmailID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vote_VoteID`
    FOREIGN KEY (`VoteID`)
    REFERENCES `voting_app`.`vote` (`VoteID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `voting_app`.`resultdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_app`.`resultdetail` (
  `ResultDetailID` CHAR(36) NOT NULL,
  `ResultID` CHAR(36) NOT NULL,
  `AnswerID` CHAR(36) NOT NULL,
  PRIMARY KEY (`ResultDetailID`),
  INDEX `resultdetail_ibfk_1` (`ResultID` ASC) VISIBLE,
  INDEX `resultdetail_ibfk_2` (`AnswerID` ASC) VISIBLE,
  CONSTRAINT `resultdetail_ibfk_1`
    FOREIGN KEY (`ResultID`)
    REFERENCES `voting_app`.`result` (`ResultID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `resultdetail_ibfk_2`
    FOREIGN KEY (`AnswerID`)
    REFERENCES `voting_app`.`answer` (`AnswerID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
